---
- hosts: dc
  roles:
    - dc
    - common
  tags: dc

- hosts: wef
  roles:
    - wef
    - common
  tags: wef

- hosts: win11
  roles:
    - win11
    - common
  tags: win11

- hosts: exchange
  roles:
    - exchange
    - common
  tags: exchange