---
- hosts: logger
  roles:
    - logger
  tags: logger

- hosts: dc
  roles:
    - dc
    - common
  tags: dc

- hosts: wef
  roles:
    - wef
    - common
  tags: wef

- hosts: exchange
  roles:
    - exchange
    - common
  tags: exchange

- hosts: win11
  roles:
    - win11
    - common
  tags: win11


